/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolconatributos;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author Manana
 */
public class ArbolConAtributo extends javax.swing.JFrame {
    
    private TreeNode raiz;
    private void crearArbol() {
        raiz = new DefaultMutableTreeNode("Equipos");
        
        DefaultMutableTreeNode [] divisiones = new DefaultMutableTreeNode[3];
        for(int i=0; i<3; i++) {
            divisiones[i] = new DefaultMutableTreeNode("Division " + (i+1));
        }
        
        divisiones[0].add( new DefaultMutableTreeNode( new Equipo("Nombre", 20, 12345342, "Bernabeu") ) );
        
        
    }

    int[] aficionados = {12345342, 34252435, 23542345, 243424, 342423134, 13123123, 132123413, 436345, 325765};
    int[] jugadores = {20, 30, 23, 10, 35, 23, 24, 76, 45};
    String[] estadio = {"Bernabeu", "Camp Nou", "Sanchez", "Cartuja", "Old", "Wanda", "Vicente", "Carlos Belmonte", "Benito Villamarin"};

    /**
     * Creates new form ArbolConAtributo
     */
    public ArbolConAtributo() {
        crearArbol();
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree(raiz);
        texto1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Futbol");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Division1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Real Madrid");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Barcelona");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alaves");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Division2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("A Coruña");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Almeria");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Zaragoza");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Division3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Zamora");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Avila");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Leon");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        texto.setColumns(20);
        texto.setRows(5);
        texto1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        String equipo = nodoSeleccionado.toString();
        StringBuilder contenido= new StringBuilder();
        if (equipo.equalsIgnoreCase("Real Madrid")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[0]+" aficionados \n");
            contenido.append("Tiene "+jugadores[0]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[0]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Barcelona")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[1]+" aficionados \n");
            contenido.append("Tiene "+jugadores[1]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[1]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Alaves")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[2]+" aficionados \n");
            contenido.append("Tiene "+jugadores[2]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[2]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("A Coruña")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[3]+" aficionados \n");
            contenido.append("Tiene "+jugadores[3]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[3]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Almeria")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[4]+" aficionados \n");
            contenido.append("Tiene "+jugadores[4]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[4]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Zaragoza")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[5]+" aficionados \n");
            contenido.append("Tiene "+jugadores[5]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[5]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Zamora")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[6]+" aficionados \n");
            contenido.append("Tiene "+jugadores[6]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[6]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Avila")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[7]+" aficionados \n");
            contenido.append("Tiene "+jugadores[7]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[7]+" \n");
            texto.setText(contenido.toString());
        }
        if (equipo.equalsIgnoreCase("Leon")) {
            contenido.append("El equipo seleccionado es: "+equipo+"\n");
            contenido.append("Tiene "+aficionados[8]+" aficionados \n");
            contenido.append("Tiene "+jugadores[8]+" jugadores \n");
            contenido.append("Su estadio es: "+estadio[8]+" \n");
            texto.setText(contenido.toString());
        }
    }//GEN-LAST:event_arbolValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolConAtributo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    private javax.swing.JScrollPane texto1;
    // End of variables declaration//GEN-END:variables
}
