/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package doblepassword;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Manana
 */
public class DoblePassword extends javax.swing.JPanel {

    /**
     * Creates new form DoblePassword
     */
    public DoblePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contraseña1 = new javax.swing.JPasswordField();
        Contraseña2 = new javax.swing.JPasswordField();
        tick2 = new javax.swing.JLabel();
        comprob = new javax.swing.JButton();
        obtener = new javax.swing.JButton();

        Contraseña1.setText("jPasswordField1");

        Contraseña2.setText("jPasswordField2");
        Contraseña2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Contraseña2FocusLost(evt);
            }
        });

        tick2.setText("  ");

        comprob.setText("Comprobar");
        comprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobActionPerformed(evt);
            }
        });

        obtener.setText("Obtener contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tick2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obtener))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(comprob)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tick2)
                    .addComponent(obtener))
                .addGap(18, 18, 18)
                .addComponent(comprob)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobActionPerformed



    }//GEN-LAST:event_comprobActionPerformed

    private void Contraseña2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Contraseña2FocusLost
        // TODO add your handling code here:
        String contra1=new String (Contraseña1.getPassword());
        String contra2=new String(Contraseña2.getPassword());
        if (contra1.contentEquals(contra2)) {
            tick2.setText("V");
            tick2.setForeground(Color.GREEN);
    }   else{
            tick2.setText("F");
            tick2.setForeground(Color.red);
    }
    }//GEN-LAST:event_Contraseña2FocusLost
    public boolean checkear(){
            String contra1=Contraseña1.getPassword().toString();
        String contra2=Contraseña2.getPassword().toString();
        
        return contra1.contentEquals(contra2);
    }
    public String obtener(){
        if (checkear()) {
            return new String(Contraseña1.getPassword());
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña1;
    private javax.swing.JPasswordField Contraseña2;
    private javax.swing.JButton comprob;
    private javax.swing.JButton obtener;
    private javax.swing.JLabel tick2;
    // End of variables declaration//GEN-END:variables
}
