/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exameninterfaces2alejandrozurron;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Point;
import java.util.Random;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manana
 */
public class Examen2Evaluacion extends javax.swing.JFrame {
private Point puntoPopup;
    /**
     * Creates new form Examen2Evaluacion
     */
    public Examen2Evaluacion() {
        initComponents();
        JComboBox<String> comboBox = new JComboBox<>(new String[]{java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("AVILA"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("BURGOS"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("LEON"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("PALENCIA"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("SALAMANCA"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("SEGOVIA"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("SORIA"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("VALLADOLID"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("ZAMORA")});
        tabla.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(new Combobox()));
        tabla.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        c.setBackground(Color.red);
        return c;
        
    }
});

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        Insertar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Seleccionartodo = new javax.swing.JMenuItem();
        mapa = new javax.swing.JPanel();
        mapa2 = new javax.swing.JLabel();
        tablaa = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        termostato1 = new exameninterfaces2alejandrozurron.Termostato();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle"); // NOI18N
        Insertar.setText(bundle.getString("Examen2Evaluacion.Insertar.text")); // NOI18N
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        menu.add(Insertar);

        Eliminar.setText(bundle.getString("Examen2Evaluacion.Eliminar.text")); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menu.add(Eliminar);

        Seleccionartodo.setText(bundle.getString("Examen2Evaluacion.Seleccionartodo.text")); // NOI18N
        Seleccionartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionartodoActionPerformed(evt);
            }
        });
        menu.add(Seleccionartodo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapaMouseClicked(evt);
            }
        });

        mapa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exameninterfaces2alejandrozurron/Mapa Castilla y Leon.png"))); // NOI18N

        javax.swing.GroupLayout mapaLayout = new javax.swing.GroupLayout(mapa);
        mapa.setLayout(mapaLayout);
        mapaLayout.setHorizontalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mapaLayout.setVerticalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapa2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, Short.MAX_VALUE)
        );

        tabla.setComponentPopupMenu(menu);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Salamanca", "1/02/2025", "12"},
                {"Salamanca", "1/02/2025", "16"},
                {"Salamanca", "1/02/2025", "20"},
                {"Salamanca", "1/02/2025", "24"},
                {"Salamanca", "1/02/2025", "30"},
                {"Ávila", "1/02/2025", "10"},
                {"Ávila", "1/02/2025", "14"},
                {"Ávila", "1/02/2025", "19"},
                {"Ávila", "1/02/2025", "22"},
                {"Ávila", "1/02/2025", "27"},
                {"Zamora", "1/02/2025", "14"},
                {"Zamora", "1/02/2025", "18"},
                {"Zamora", "1/02/2025", "22"},
                {"Zamora", "1/02/2025", "27"},
                {"Zamora", "1/02/2025", "32"}
            },
            new String [] {
                "LOCALIDAD", "FECHA", "TEMPERATURA MAX (ºC)"
            }
        ));
        tablaa.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tablaa, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(termostato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(tablaa, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(termostato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        // TODO add your handling code here:
        
        ((DefaultTableModel)tabla.getModel()).insertRow(tabla.rowAtPoint(puntoPopup),new Object[] {null,null,null,null});

        
    }//GEN-LAST:event_InsertarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int respuesta= JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("ESTAS SEGURO"),java.util.ResourceBundle.getBundle("exameninterfaces2alejandrozurron/Bundle").getString("BORRAR"),JOptionPane.YES_NO_OPTION);
        if (respuesta==JOptionPane.YES_OPTION) {
            
        
        int[] filas= tabla.getSelectedRows();
        if (filas.length>0) {
            for (int i=filas.length-1;i>=0;i--) {
                
            ((DefaultTableModel)tabla.getModel()).removeRow(filas[i]);
            }
        }
        }
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void SeleccionartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionartodoActionPerformed
        // TODO add your handling code here:
        tabla.selectAll();
    }//GEN-LAST:event_SeleccionartodoActionPerformed

    private void mapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMouseClicked
        // TODO add your handling code here:
                    Graphics gVentana = mapa.getGraphics();
                    gVentana.setColor(Color.ORANGE);
                    gVentana.fillOval(evt.getX(), evt.getY(), 15, 15);
                    gVentana.drawLine(evt.getX()+7, evt.getY()+20,evt.getX()+7, evt.getY()-5);
                    gVentana.drawLine(evt.getX()+20, evt.getY()+7,evt.getX()-5, evt.getY()+7);
    }//GEN-LAST:event_mapaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2Evaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Insertar;
    private javax.swing.JMenuItem Seleccionartodo;
    private javax.swing.JPanel mapa;
    private javax.swing.JLabel mapa2;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablaa;
    private exameninterfaces2alejandrozurron.Termostato termostato1;
    // End of variables declaration//GEN-END:variables
}
