/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aazur
 */
public class Paintt extends javax.swing.JFrame {

    enum Opciones {
        PINTAR,
        CIRCULOS,
        NADA,
        BORRAR

    }
    Opciones seleccion = Opciones.NADA;

    private BufferedImage imagen;
    private Point anterior = null;
    private Color colorseleccionado = Color.BLACK;
    private static final int TAMANO_CIRCULO = 50;

    /**
     * Creates new form Paintt
     */
    public Paintt() {
        initComponents();
        imagen = new BufferedImage(800, 600, BufferedImage.TYPE_INT_ARGB);
        getContentPane().setBackground(Color.WHITE);
        // Llena el fondo con blanco
        Graphics g = imagen.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, imagen.getWidth(), imagen.getHeight());
        g.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Guardar = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lienzo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Pintar = new javax.swing.JMenu();
        Circulos = new javax.swing.JMenu();
        Colorr = new javax.swing.JMenu();
        Exportar = new javax.swing.JMenu();
        Clear2 = new javax.swing.JMenu();
        Borrar2 = new javax.swing.JMenu();
        Manual = new javax.swing.JMenu();
        Acercade = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/69539.png"))); // NOI18N
        Guardar.setFocusable(false);
        Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(Guardar);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7046041.png"))); // NOI18N
        Clear.setFocusable(false);
        Clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jToolBar1.add(Clear);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/732397.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        lienzo.setBackground(new java.awt.Color(255, 255, 255));
        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lienzoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        Pintar.setText("Pintar");
        Pintar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PintarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Pintar);

        Circulos.setText("Circulos");
        Circulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CirculosMouseClicked(evt);
            }
        });
        jMenuBar1.add(Circulos);

        Colorr.setText("Color");
        Colorr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorrMouseClicked(evt);
            }
        });
        jMenuBar1.add(Colorr);

        Exportar.setText("Exportar");
        Exportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Exportar);

        Clear2.setText("Clear");
        Clear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear2MouseClicked(evt);
            }
        });
        jMenuBar1.add(Clear2);

        Borrar2.setText("Borrar");
        Borrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Borrar2MouseClicked(evt);
            }
        });
        jMenuBar1.add(Borrar2);

        Manual.setText("Manual");
        Manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManualMouseClicked(evt);
            }
        });
        jMenuBar1.add(Manual);

        Acercade.setText("Acerca de");
        Acercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcercadeMouseClicked(evt);
            }
        });
        jMenuBar1.add(Acercade);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        imagen = new BufferedImage(lienzo.getWidth(), lienzo.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics gImagen = imagen.getGraphics();
        gImagen.setColor(Color.WHITE);
        gImagen.fillRect(0, 0, imagen.getWidth(), imagen.getHeight());

    }//GEN-LAST:event_formWindowOpened

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "¿Desea guardar la imagen ?", "Guardar", JOptionPane.YES_NO_OPTION)) {
            JFileChooser dialogoArch = new JFileChooser();
            if (JFileChooser.APPROVE_OPTION == dialogoArch.showSaveDialog(this)) {
                File arch = dialogoArch.getSelectedFile();
                try {
                    ImageIO.write(imagen, "png", arch);
                } catch (IOException ex) {
                }
            }
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        imagen = new BufferedImage(getContentPane().getWidth(), getContentPane().getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics gImagen = imagen.getGraphics();
        gImagen.setColor(Color.WHITE);
        gImagen.fillRect(0, 0, imagen.getWidth(), imagen.getHeight());
        repaint();
    }//GEN-LAST:event_ClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
                if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "¿Desea guardar la imagen ?", "Guardar", JOptionPane.YES_NO_OPTION)) {
            JFileChooser dialogoArch = new JFileChooser();
            if (JFileChooser.APPROVE_OPTION == dialogoArch.showSaveDialog(this)) {
                File arch = dialogoArch.getSelectedFile();
                try {
                    ImageIO.write(imagen, "png", arch);
                } catch (IOException ex) {
                }
            }
        }

    }//GEN-LAST:event_formWindowClosing

    private void PintarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PintarMouseClicked
        // TODO add your handling code here:
        seleccion = Opciones.PINTAR;
    }//GEN-LAST:event_PintarMouseClicked

    private void CirculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CirculosMouseClicked
        // TODO add your handling code here:
        seleccion = Opciones.CIRCULOS;
    }//GEN-LAST:event_CirculosMouseClicked

    private void ColorrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorrMouseClicked
        // TODO add your handling code here:
         Color opcion = JColorChooser.showDialog(this, "Elige", Color.yellow);
        Graphics gVentana = getGraphics();
        Graphics gImagen = imagen.getGraphics();
        if (opcion != null) {
            colorseleccionado = opcion;
        }
    }//GEN-LAST:event_ColorrMouseClicked

    private void ExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportarMouseClicked
        // TODO add your handling code here:
                        if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "¿Desea guardar la imagen ?", "Guardar", JOptionPane.YES_NO_OPTION)) {
            JFileChooser dialogoArch = new JFileChooser();
            if (JFileChooser.APPROVE_OPTION == dialogoArch.showSaveDialog(this)) {
                File arch = dialogoArch.getSelectedFile();
                try {
                    ImageIO.write(imagen, "png", arch);
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_ExportarMouseClicked

    private void Clear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear2MouseClicked
        // TODO add your handling code here:
                imagen = new BufferedImage(lienzo.getWidth(), lienzo.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics gImagen = imagen.getGraphics();
        gImagen.setColor(Color.WHITE);
        gImagen.fillRect(0, 0, imagen.getWidth(), imagen.getHeight());
        repaint();
    }//GEN-LAST:event_Clear2MouseClicked

    private void Borrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrar2MouseClicked
        // TODO add your handling code here:
        seleccion = Opciones.BORRAR;
    }//GEN-LAST:event_Borrar2MouseClicked

    private void ManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManualMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ManualMouseClicked

    private void AcercadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcercadeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog(this, "El autor de esto es muy inteligente");
    }//GEN-LAST:event_AcercadeMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
                        if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "¿Desea guardar la imagen ?", "Guardar", JOptionPane.YES_NO_OPTION)) {
            JFileChooser dialogoArch = new JFileChooser();
            if (JFileChooser.APPROVE_OPTION == dialogoArch.showSaveDialog(this)) {
                File arch = dialogoArch.getSelectedFile();
                try {
                    ImageIO.write(imagen, "png", arch);
                } catch (IOException ex) {
                }
            }
        }

    }//GEN-LAST:event_SalirMouseClicked

    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        // TODO add your handling code here:
             if (null != seleccion) // TODO add your handling code here:
            switch (seleccion) {
                case CIRCULOS: {
                    Random rand = new Random();
                    int tamano = rand.nextInt(81) + 20;
                    Graphics gVentana = lienzo.getGraphics();
                    Graphics gImagen = imagen.getGraphics();
                    gVentana.setColor(colorseleccionado);
                    gImagen.setColor(colorseleccionado);
                    int x = evt.getX() - TAMANO_CIRCULO / 2;
                    int y = evt.getY() - TAMANO_CIRCULO / 2;

                    gVentana.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    gImagen.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    break;
                }
                case PINTAR:
                    if (anterior == null) {
                        anterior = evt.getPoint();
                    } else {
                        Graphics gVentana = lienzo.getGraphics();
                        Graphics gImagen = imagen.getGraphics();
                        gVentana.setColor(colorseleccionado);
                        gImagen.setColor(colorseleccionado);

                        gVentana.drawLine(anterior.x, anterior.y, evt.getX(), evt.getY());
                        gImagen.drawLine(anterior.x, anterior.y, evt.getX(), evt.getY());

                        anterior = evt.getPoint();

                        gImagen.dispose();
                    }
                    break;
                case BORRAR: {
                    Random rand = new Random();
                    int tamano = rand.nextInt(81) + 20;
                    Graphics gVentana = lienzo.getGraphics();
                    Graphics gImagen = imagen.getGraphics();
                    gVentana.setColor(Color.WHITE);
                    gImagen.setColor(Color.white);
                    int x = evt.getX() - TAMANO_CIRCULO / 2;
                    int y = evt.getY() - TAMANO_CIRCULO / 2;

                    gVentana.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    gImagen.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    break;
                }
                default:
                    break;
            }
   
    }//GEN-LAST:event_lienzoMouseDragged

    private void lienzoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseClicked
        // TODO add your handling code here:
             if (null != seleccion) // TODO add your handling code here:
            switch (seleccion) {
                case CIRCULOS: {
                    Random rand = new Random();
                    int tamano = rand.nextInt(81) + 20;
                    Graphics gVentana = lienzo.getGraphics();
                    Graphics gImagen = imagen.getGraphics();
                    gVentana.setColor(colorseleccionado);
                    gImagen.setColor(colorseleccionado);
                    int x = evt.getX() - TAMANO_CIRCULO / 2;
                    int y = evt.getY() - TAMANO_CIRCULO / 2;

                    gVentana.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    gImagen.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    break;
                }
                case PINTAR:
                    if (anterior == null) {
                        anterior = evt.getPoint();
                    } else {
                        Graphics gVentana = lienzo.getGraphics();
                        Graphics gImagen = imagen.getGraphics();
                        gVentana.setColor(colorseleccionado);
                        gImagen.setColor(colorseleccionado);

                        gVentana.drawLine(anterior.x, anterior.y, evt.getX(), evt.getY());
                        gImagen.drawLine(anterior.x, anterior.y, evt.getX(), evt.getY());

                        anterior = evt.getPoint();

                        gImagen.dispose();
                    }
                    break;
                case BORRAR: {
                    Random rand = new Random();
                    int tamano = rand.nextInt(81) + 20;
                    Graphics gVentana = lienzo.getGraphics();
                    Graphics gImagen = imagen.getGraphics();
                    gVentana.setColor(Color.WHITE);
                    gImagen.setColor(Color.white);
                    int x = evt.getX() - TAMANO_CIRCULO / 2;
                    int y = evt.getY() - TAMANO_CIRCULO / 2;

                    gVentana.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    gImagen.fillOval(x, y, TAMANO_CIRCULO, TAMANO_CIRCULO);
                    break;
                }
                default:
                    break;
            }
   
    }//GEN-LAST:event_lienzoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paintt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paintt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paintt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paintt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paintt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acercade;
    private javax.swing.JMenu Borrar2;
    private javax.swing.JMenu Circulos;
    private javax.swing.JButton Clear;
    private javax.swing.JMenu Clear2;
    private javax.swing.JMenu Colorr;
    private javax.swing.JMenu Exportar;
    private javax.swing.JButton Guardar;
    private javax.swing.JMenu Manual;
    private javax.swing.JMenu Pintar;
    private javax.swing.JMenu Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel lienzo;
    // End of variables declaration//GEN-END:variables
}
