/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolconatributos;

import arbolconatributos.Equipo;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author Manana
 */
public class ArbolConAtributo extends javax.swing.JFrame {

    private DefaultMutableTreeNode raiz;

    private void crearArbol() {
        raiz = new DefaultMutableTreeNode("Equipos");

        DefaultMutableTreeNode[] divisiones = new DefaultMutableTreeNode[3];
        for (int i = 0; i < 3; i++) {
            divisiones[i] = new DefaultMutableTreeNode("Division " + (i + 1));
            raiz.add(divisiones[i]);
        }

        divisiones[0].add(new DefaultMutableTreeNode(new Equipo("Real Madrid", 20, 12345342, "Bernabeu")));
        divisiones[0].add(new DefaultMutableTreeNode(new Equipo("Barcelona", 20, 12345342, "Bernabeu")));
        divisiones[0].add(new DefaultMutableTreeNode(new Equipo("Alaves", 20, 12345342, "Bernabeu")));
        divisiones[1].add(new DefaultMutableTreeNode(new Equipo("Zaragoza", 20, 12345342, "Bernabeu")));
        divisiones[1].add(new DefaultMutableTreeNode(new Equipo("Almeria", 20, 12345342, "Bernabeu")));
        divisiones[1].add(new DefaultMutableTreeNode(new Equipo("Celta", 20, 12345342, "Bernabeu")));
        divisiones[2].add(new DefaultMutableTreeNode(new Equipo("Zamora", 20, 12345342, "Bernabeu")));
        divisiones[2].add(new DefaultMutableTreeNode(new Equipo("Avila", 20, 12345342, "Bernabeu")));
        divisiones[2].add(new DefaultMutableTreeNode(new Equipo("Leon", 20, 12345342, "Bernabeu")));
    }

    /**
     * Creates new form ArbolConAtributo
     */
    public ArbolConAtributo() {
        crearArbol();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree(raiz);
        texto1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        texto.setColumns(20);
        texto.setRows(5);
        texto1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbol.getLastSelectedPathComponent();
        StringBuilder contenido = new StringBuilder();
        if (nodoSeleccionado.isLeaf()) {
            Equipo equipo = (Equipo) nodoSeleccionado.getUserObject();
            contenido.append("El equipo seleccionado es: " + equipo.getNombre() + "\n");
            contenido.append("Tiene " + equipo.getAficionados() + " aficionados \n");
            contenido.append("Tiene " + equipo.getJugadores() + " jugadores \n");
            contenido.append("Su estadio es: " + equipo.getEstadio() + " \n");
            texto.setText(contenido.toString());
        }

    }//GEN-LAST:event_arbolValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolConAtributo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolConAtributo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    private javax.swing.JScrollPane texto1;
    // End of variables declaration//GEN-END:variables
}
