/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacescasa;

import static java.lang.reflect.Array.get;
import static java.nio.file.Paths.get;
import java.util.Random;
import javax.swing.ImageIcon;
import static javax.swing.UIManager.get;

/**
 *
 * @author Manana
 */
public class Juego_PPT extends javax.swing.JFrame {

    int contJ = 0;
    int contM = 0;

    enum Resultado {
        Piedra,
        Papel,
        Tijera,
        Ninguna
    }
    Resultado operacion = Resultado.Ninguna;
    String jugador = "";
    Random rd = new Random(3);

    /**
     * Creates new form Juego_PPT
     */
    public Juego_PPT() {
        initComponents();
        this.setIconImage(new ImageIcon (getClass().getResource("resources/png-clipart-lightbulb-light-bulb-bulb.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Victorias:");

        jTextField2.setEditable(false);
        jTextField2.setText("Victorias:");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Piedra");
        jRadioButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\file2.jpg")); // NOI18N
        jRadioButton1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\aa.png")); // NOI18N
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Papel");
        jRadioButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\file(1).jpg")); // NOI18N
        jRadioButton2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\file(1).png")); // NOI18N
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Tijera");
        jRadioButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\file.png")); // NOI18N
        jRadioButton3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Manana\\Desktop\\Interfaces\\Interfacescasa\\imagenes\\file(2).png")); // NOI18N
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("PIEDRA-PAPEL-TIJERA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField4.setText("Jugador");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField5.setText("Máquina");

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Resultado");

        jLabel4.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel4.setMinimumSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(174, 174, 174))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /* Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];

        if (jRadioButton1.isSelected()) {
            operacion = Resultado.Piedra;
        } else if (jRadioButton2.isSelected()) {
            operacion = Resultado.Papel;
        } else if (jRadioButton3.isSelected()) {
            operacion = Resultado.Tijera;
        }
        ImageIcon iconop = new ImageIcon("imagenes\\file2.jpg");
        ImageIcon iconopap = new ImageIcon("imagenes\\file(1).jpg");
        ImageIcon iconotij = new ImageIcon("imagenes\\file.png");
        if (maquina == Resultado.Piedra) {
            jLabel4.setIcon(iconop);

        } else if (maquina == Resultado.Papel) {
            jLabel4.setIcon(iconopap);
        } else if (maquina == Resultado.Tijera) {
            jLabel4.setIcon(iconotij);

        }

        switch (operacion) {
            case Piedra:
                if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Empate");

                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;
            case Papel:
                if (maquina == Resultado.Papel) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;

                }
                break;
            case Tijera:
                if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;

        }
        jTextField1.setText("Victorias:" + contJ);
        jTextField2.setText("Victorias:" + contM);
*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
                Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];
           ImageIcon iconop = new ImageIcon("imagenes\\file2.jpg");
        ImageIcon iconopap = new ImageIcon("imagenes\\file(1).jpg");
        ImageIcon iconotij = new ImageIcon("imagenes\\file.png");
        operacion=Resultado.Piedra;
        if (maquina == Resultado.Piedra) {
            jLabel4.setIcon(iconop);

        } else if (maquina == Resultado.Papel) {
            jLabel4.setIcon(iconopap);
        } else if (maquina == Resultado.Tijera) {
            jLabel4.setIcon(iconotij);

        }

        switch (operacion) {
            case Piedra:
                if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Empate");

                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;
            case Papel:
                if (maquina == Resultado.Papel) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;

                }
                break;
            case Tijera:
                if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;

        }
        jTextField1.setText("Victorias:" + contJ);
        jTextField2.setText("Victorias:" + contM);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
                Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];
        operacion=Resultado.Papel;
           ImageIcon iconop = new ImageIcon("imagenes\\file2.jpg");
        ImageIcon iconopap = new ImageIcon("imagenes\\file(1).jpg");
        ImageIcon iconotij = new ImageIcon("imagenes\\file.png");
        if (maquina == Resultado.Piedra) {
            jLabel4.setIcon(iconop);

        } else if (maquina == Resultado.Papel) {
            jLabel4.setIcon(iconopap);
        } else if (maquina == Resultado.Tijera) {
            jLabel4.setIcon(iconotij);

        }

        switch (operacion) {
            case Piedra:
                if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Empate");

                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;
            case Papel:
                if (maquina == Resultado.Papel) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;

                }
                break;
            case Tijera:
                if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;

        }
        jTextField1.setText("Victorias:" + contJ);
        jTextField2.setText("Victorias:" + contM);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        // TODO add your handling code here:
                Resultado[] posibilidades = Resultado.values();
        Resultado maquina = posibilidades[rd.nextInt(3)];
        operacion=Resultado.Tijera;
           ImageIcon iconop = new ImageIcon("imagenes\\file2.jpg");
        ImageIcon iconopap = new ImageIcon("imagenes\\file(1).jpg");
        ImageIcon iconotij = new ImageIcon("imagenes\\file.png");
        
        if (maquina == Resultado.Piedra) {
            jLabel4.setIcon(iconop);

        } else if (maquina == Resultado.Papel) {
            jLabel4.setIcon(iconopap);
        } else if (maquina == Resultado.Tijera) {
            jLabel4.setIcon(iconotij);

        }

        switch (operacion) {
            case Piedra:
                if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Empate");

                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;
            case Papel:
                if (maquina == Resultado.Papel) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;

                }
                break;
            case Tijera:
                if (maquina == Resultado.Tijera) {
                    jTextField7.setText("Empate");
                } else if (maquina == Resultado.Piedra) {
                    jTextField7.setText("Gana Maquina");
                    contM++;
                } else if (maquina == Resultado.Papel) {
                    jTextField7.setText("Gana Jugador");
                    contJ++;
                }
                break;

        }
        jTextField1.setText("Victorias:" + contJ);
        jTextField2.setText("Victorias:" + contM);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_PPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_PPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
