/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestor;

import gestor.modelo.Contacto;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zurrón
 */
public class Gestor extends javax.swing.JFrame {
   ArrayList <Contacto> contact= new ArrayList<>();
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Colores = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Categoriaf = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        Telefonof = new javax.swing.JTextField();
        Emailf = new javax.swing.JTextField();
        Nombref = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        guardarT = new javax.swing.JButton();
        verT = new javax.swing.JButton();
        ayudaT = new javax.swing.JButton();
        eliminarT = new javax.swing.JButton();
        salirT = new javax.swing.JButton();
        barra = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Guardarlista = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();
        Ver = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Email", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Colores.addTab("Tabla", panel);

        panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nombre");

        jLabel2.setText("Telefono");

        jLabel3.setText("Email");

        jLabel4.setText("Categoria");

        Categoriaf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amigos", "Familia", "Trabajo" }));

        jLabel5.setText("FORMULARIO NUEVO CONTACTO");

        Añadir.setText("Añadir contacto");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(162, 162, 162))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nombref, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emailf, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(Telefonof, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35)
                                        .addComponent(Categoriaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Añadir)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(Categoriaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefonof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Emailf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Añadir)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Colores.addTab("Formulario", panel2);

        panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        Colores.addTab("Colores", panel3);

        jToolBar1.setRollover(true);

        guardarT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zurrón\\OneDrive\\Documentos\\NetBeansProjects\\Gestor\\359316.png")); // NOI18N
        guardarT.setFocusable(false);
        guardarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTActionPerformed(evt);
            }
        });
        jToolBar1.add(guardarT);

        verT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zurrón\\OneDrive\\Documentos\\NetBeansProjects\\Gestor\\rueda-de-colores-734x733.jpg")); // NOI18N
        verT.setFocusable(false);
        verT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTActionPerformed(evt);
            }
        });
        jToolBar1.add(verT);

        ayudaT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zurrón\\OneDrive\\Documentos\\NetBeansProjects\\Gestor\\pngtree-sign-with-the-word-help-in-a-hand-icon-png-image_1773655.jpg")); // NOI18N
        ayudaT.setToolTipText("");
        ayudaT.setFocusable(false);
        ayudaT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ayudaT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ayudaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTActionPerformed(evt);
            }
        });
        jToolBar1.add(ayudaT);

        eliminarT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zurrón\\OneDrive\\Documentos\\NetBeansProjects\\Gestor\\png-transparent-letter-x-illustration-x-mark-check-mark-desktop-x-mark-miscellaneous-angle-flag-thumbnail.png")); // NOI18N
        eliminarT.setFocusable(false);
        eliminarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTActionPerformed(evt);
            }
        });
        jToolBar1.add(eliminarT);

        salirT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zurrón\\OneDrive\\Documentos\\NetBeansProjects\\Gestor\\images.jpg")); // NOI18N
        salirT.setFocusable(false);
        salirT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirTActionPerformed(evt);
            }
        });
        jToolBar1.add(salirT);

        Archivo.setText("Archivo");

        Guardarlista.setText("Guardar");
        Guardarlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarlistaMouseClicked(evt);
            }
        });
        Archivo.add(Guardarlista);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        Archivo.add(Salir);

        barra.add(Archivo);

        Ver.setText("Ver");
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerMouseClicked(evt);
            }
        });
        barra.add(Ver);

        Ayuda.setText("Ayuda");
        Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyudaMouseClicked(evt);
            }
        });
        barra.add(Ayuda);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Colores, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Colores, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        if (Nombref.getText().equalsIgnoreCase("")||Emailf.getText().equalsIgnoreCase("")||Telefonof.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this,"TIENES QUE AÑADIR TODA LA INFORMACIÓN");
        }else {
        String nombre=Nombref.getText();
        String email=Emailf.getText();
        String telefono=Telefonof.getText();
        String categoria=(String)Categoriaf.getSelectedItem(); //CHEKAR ERRORES
        Contacto cont= new Contacto(nombre,email,telefono,categoria);
        contact.add(cont);
        ((DefaultTableModel)Tabla.getModel()).addRow(new Object[]{nombre,email,telefono,categoria});
        
        }
        
    }//GEN-LAST:event_AñadirActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        int result= JOptionPane.showConfirmDialog(this, "Salir", "¿Estas seguro?",JOptionPane.YES_NO_OPTION);
        if (result==JOptionPane.YES_OPTION) {
         this.dispose();
        }
    }//GEN-LAST:event_SalirMouseClicked

    private void GuardarlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarlistaMouseClicked
        // TODO add your handling code here:
        JFileChooser file= new JFileChooser();
        int eleccion=file.showSaveDialog(this);
        
        if (eleccion==JOptionPane.YES_OPTION) {
            
            try {
                File archivo= file.getSelectedFile();
                BufferedWriter oos = new BufferedWriter(new FileWriter(archivo));
                String con;
                int cont=1;
                for (Contacto contacto : contact) {
                    con="Contacto"+cont+": "+contacto.getNombre()+","+contacto.getEmail()+","+contacto.getTelefono()+","+contacto.getCategoria();
                    oos.write(con);
                    oos.newLine();
                    cont++;
                }
                oos.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Gestor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Gestor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_GuardarlistaMouseClicked

    private void VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseClicked
        // TODO add your handling code here:
        Color colorseleccionado=JColorChooser.showDialog(this, "Elige un color", getBackground());
        if (colorseleccionado!=null) {
        panel.setBackground(colorseleccionado);
        panel2.setBackground(colorseleccionado);
        panel3.setBackground(colorseleccionado);
        Tabla.setBackground(colorseleccionado);
        }

    }//GEN-LAST:event_VerMouseClicked

    private void AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Informacion \n"
                + "Este gestor de contactos esta creado ni más ni menos por el mismisimo Alejandro");
    }//GEN-LAST:event_AyudaMouseClicked

    private void verTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTActionPerformed
        // TODO add your handling code here:
                Color colorseleccionado=JColorChooser.showDialog(this, "Elige un color", getBackground());
        if (colorseleccionado!=null) {
        panel.setBackground(colorseleccionado);
        panel2.setBackground(colorseleccionado);
        panel3.setBackground(colorseleccionado);
        Tabla.setBackground(colorseleccionado);
        }

    }//GEN-LAST:event_verTActionPerformed

    private void guardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTActionPerformed
        // TODO add your handling code here:
                JFileChooser file= new JFileChooser();
        int eleccion=file.showSaveDialog(this);
        
        if (eleccion==JOptionPane.YES_OPTION) {
            
            try {
                File archivo= file.getSelectedFile();
                BufferedWriter oos = new BufferedWriter(new FileWriter(archivo));
                String con;
                int cont=1;
                for (Contacto contacto : contact) {
                    con="Contacto"+cont+": "+contacto.getNombre()+","+contacto.getEmail()+","+contacto.getTelefono()+","+contacto.getCategoria();
                    oos.write(con);
                    oos.newLine();
                }
                oos.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Gestor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Gestor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_guardarTActionPerformed

    private void ayudaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTActionPerformed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "Informacion \n"
                + "Este gestor de contactos esta creado ni más ni menos por el mismisimo Alejandro");
    }//GEN-LAST:event_ayudaTActionPerformed

    private void eliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTActionPerformed
        // TODO add your handling code here:
        int [] eliminar=Tabla.getSelectedRows();
         for (int i= eliminar.length-1; i>=0;i--) {
            ((DefaultTableModel)Tabla.getModel()).removeRow(eliminar[i]);
        }
    }//GEN-LAST:event_eliminarTActionPerformed

    private void salirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirTActionPerformed
        // TODO add your handling code here:
                int result= JOptionPane.showConfirmDialog(this, "Salir", "¿Estas seguro?",JOptionPane.YES_NO_OPTION);
        if (result==JOptionPane.YES_OPTION) {
         this.dispose();
        }
    }//GEN-LAST:event_salirTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JButton Añadir;
    private javax.swing.JComboBox<String> Categoriaf;
    private javax.swing.JTabbedPane Colores;
    private javax.swing.JTextField Emailf;
    private javax.swing.JMenu Guardarlista;
    private javax.swing.JTextField Nombref;
    private javax.swing.JMenu Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Telefonof;
    private javax.swing.JMenu Ver;
    private javax.swing.JButton ayudaT;
    private javax.swing.JMenuBar barra;
    private javax.swing.JButton eliminarT;
    private javax.swing.JButton guardarT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JButton salirT;
    private javax.swing.JButton verT;
    // End of variables declaration//GEN-END:variables
}
